### ISSUE TITLE
download_dayment_ncss() cannot pull 2020 data

### ISSUE THREAD

**Issue by j-baldock** [bluegreen-labs/daymetr#46]
I can download single pixel data for year 2020 using the following code:

`download_daymet(site = "test", lat = 44.598173, lon = -111.092613, 
                start = 2020, end = 2020, 
                path = tempdir(), silent = FALSE, force = TRUE)`

However, when I try to download gridded data for the same time period, the following code fails:

`download_daymet_ncss(location = c(44.598173, -111.092613, 42.842560, -109.616358),
                     start = 2020, end = 2020, 
                     param = c("tmin", "tmax"), frequency = "daily",
                     path = tempdir(), silent = FALSE, force = TRUE)` 

Error message:
Error: Requested data download failed! 
             Common issues involve a mismatch between 
             the location and the mosaic used or downloads 
             exceeding 6GB in size.

In both code chunks I am using the argument "force = TRUE" to override the default maximum end year. Note that I can run the download_daymet_ncss() function on year 2019 with no issue. Also note that the location of the single pixel download is the top-left coordinate of the bounding box for the gridded download.

Please advise. Thank you.

**Comment by khufkens** [comment]
Seems that I never pushed the conversion of v3 to v4 as I had planned. This explains the error. Will fix tonight.

**Comment by khufkens** [comment]
Fixed as of https://github.com/bluegreen-labs/daymetr/commit/b571ffcacaaec82c6732b839c80daf95d357c5a3

This is a new release (1.5) as fixing the issue, made me realize why I put it off in the first  place (a whole slew of other things needed fixing due to recent changes in GDAL and the move from PROJ4 to PROJ6).

Please install from github for the time being, the formal release will happen next week or so.
