### ISSUE TITLE
Cannot Open Daymet Files

### ISSUE THREAD

**Issue by kbondo1** [bluegreen-labs/daymetr#53]
I recently tried using the daymetr package to download Daymet data for specific tiles (e.g., 11570 for the years 2017-2020). The files downloaded using the daymetr package are different in size from the ones I download manually from the Daymet (ornldaac) webpage and cannot be opened in R using any method I have tried. I obtain an R error message saying that the files are of an unknown file format. This seems to be a more recent issue as in 2021 when I tried to use the daymetr package to download the files for years up until 2020, I obtained the exact same files that I downloaded manually from the webpage. For some reason, I was never able to download files that could be opened from the year 2020 using the daymetr package, but now when I try to download the files for any year, they are all unreadable. The files I have recently tried to download using the daymetr package are all 628 bytes in size, whereas the files that I download manually from the webpage range in size from 1.5 MB to 79.8 MB. Is this an issue with the daymetr package, or do you know how to resolve this issue?

**Comment by jeff-wagner** [comment]
I was having this same issue with the CRAN version of the package; however, this appears to have been fixed in the latest development update by @khufkens here on GitHub. I think the tile server string in the CRAN version is outdated. Try downloading the latest development version using the code below & rerunning your query. Hope this helps!

`if(!require(devtools)){install.packages("devtools")}`
`devtools::install_github("bluegreen-labs/daymetr")`
`library("daymetr")`

**Comment by khufkens** [comment]
A new version is submitted to CRAN, but software developers need holidays too so this won't be online until next week or later (should check the CRAN mailinglist for holiday dates).

Do restart your session after the github install, as the current session will retain the old version if previously loaded.

**Comment by kbondo1** [comment]
Thanks so much for all of the help resolving this issue.
